import thoipapy.figs.BoCurve_ThoipaBest_comp_LIPS_and_Nmr
import thoipapy.figs.Average_Fraction_DI
import thoipapy.figs.Preddimer_TMdock_heatmap
import thoipapy.figs.fig_utils
import thoipapy.figs.Create_Bo_Curve_files
import thoipapy.figs.Combine_Bo_Curve_files
import thoipapy.figs.Calc_PREDDIMER_TMDOCK_Closedist
import thoipapy.figs.combine_add_3_prediction